### ISSUE TITLE
elm-analyse.json does not work in some conditions

### ISSUE THREAD

**Issue by jinjor** [elm-tooling/elm-language-server#123]
ref https://github.com/elm-tooling/elm-language-server/issues/112#issuecomment-518981491

I located elm-analyse.json next to elm.json but it does not work on VSCode.

```json
{
  "checks": {
    "ImportAll": false,
    "SingleFieldRecord": false,
    "UnusedVariable": false,
    "TriggerWords": []
  }
}
```

## Expected Behavior
Configuration works (some checks should be disabled).

## Current Behavior
Configuration does not work (all checks are still enabled).

## Context

My project is monorepo-structured like this:
```
project/
  ├─ .git/
  ├─ server/
  └─ webui/
      ├── src/
      ├── elm.json
      └── elm-analyse.json
```
I opened VSCode on `project/` and on `webui/`, but configuration does not work in both situations.

## Your Environment
* Version used: 
* Editor used: VSCode
* Environment name and version (e.g. node.js 5.4):
* Operating System and version: macOS

**Comment by Razzeee** [comment]
@antew maybe you can have a look?

**Comment by andys8** [comment]
`TriggerWords` doesn't seem to be correct. It's not a check.

```json
{
  "checks": {
    "ImportAll": false
  },
  "TriggerWords": {
    "words": ["fixme"]
  }
}
```

I could reproduce the issue with your config. It's the also case when running `npx elm-analyse` in the elm directory.

I'm having a hard time finding evidence in the documentation.
https://stil4m.github.io/elm-analyse/#/messages/TriggerWords
https://stil4m.github.io/elm-analyse/#/configuration

Could you first verify, it's the case? And afterwards, we should look into `elm-analyse` documentation and find out if it can be improved. Since it seems to fail silently, `elm-language-server` isn't the causing it and can't do much about it (if my assumptions are true).

**Comment by jinjor** [comment]
Ah, you are right!
It worked after reopening VSCode. Thanks 👍 

(I also found `TriggerWords` can be switched on/off in `checks` block.)
```
{
  "checks": {
    "TriggerWords": false
  },
  "TriggerWords": {
    "words": ["TODO"]
  }
}
```

So should we close this issue or keep opening for further improvements?

**Comment by andys8** [comment]
Great. 

The one thing I thought of was verifying configuration in `elm-analyse` by @stil4m itself and if it's the case somehow show a better error message. But in my opinion it's lower priority than other issues.

And in general: Add some explanation about `elm-analyse` in `elm-language-server` #112.

So do you have further improvements in mind regarding this issue? Otherwise I'm gonna close it and I'm happy it worked out for you.

**Comment by jinjor** [comment]
I agree that it is lower priority. Documentation should be enough right now.

So I close this. Thank you 👍
