### ISSUE TITLE
diagnosticProviders

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#13]
We currently have two ways diagnostics are generated, there might be more in the future:

- elm make
- elm analyse

- [ ] Testing
- [ ] Bugfixes
- [x] Possibility to give the path to both if they're not installed global

Elm analyse works fine on windows for me.
Elm make tries to open the generated `elm.js` every time it runs. Pretty weird, hopefully just something that happens when you run the dev version.

Linux says it doesn't global installations, I do have them. So it might be my linux or a problem in general.
No idea about macOS.

**Comment by antew** [comment]
`elm-analyse` wasn't working for me on macOS, I was using the elm-spa-example for testing, it gives me this error

```
Debugger listening on ws://127.0.0.1:6010/2f37d3a6-071e-4a11-b12a-240f204573d7
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 5:19:33 PM] Rebuilding tree-sitter for local Electron version
[Info  - 5:19:33 PM] Fetching tree-sitter
[Info  - 5:19:33 PM] Downloading from https://github.com/tree-sitter/node-tree-sitter/releases/download/v0.14.0/tree-sitter-v0.14.0-electron-v64-darwin-x64.tar.gz
[Info  - 5:19:33 PM] Fetching tree-sitter-elm
[Info  - 5:19:33 PM] Downloading from https://github.com/razzeee/tree-sitter-elm/releases/download/v2.2.1/tree-sitter-elm-v2.2.1-electron-v64-darwin-x64.tar.gz
[Info  - 5:19:33 PM] Rebuild succeeded!
[Info  - 5:19:34 PM] Initializing Elm language server for workspace
 file:///Users/hpate/git/elm-spa-example using file:///Users/hpate/git/elm-spa-example/
[Info  - 5:19:34 PM] Reading elm.json from /Users/hpate/git/elm-spa-example/elm.json
[Info  - 5:19:34 PM] source-dirs found: /Users/hpate/git/elm-spa-example/src
[Info  - 5:19:34 PM] Found 33 files to add to the project
undefined:1
{"messages":[{"id":161,"status":"applicable","file":"src/Api.elm","type":"UnusedImportedVariable","data":{"description":"Unused imported variable `Expect` at ((13,29),(13,35))","properties":{"range":[13,29,13,35],"varName":"Expect"}}},{"id":167,"status":"applicable","file":"src/Api.elm","type":"UnusedImportAlias","data":{"description":"Unused import alias `Pipeline` at ((15,1),(15,70))","properties":{"moduleName":["Pipeline"],"range":[15,1,15,70]}}},{"id":162,"status":"applicable","file":"src/Api.elm","type":"UnusedImportedVariable","data":{"description":"Unused imported variable `optional` at ((15,51),(15,59))","properties":{"range":[15,51,15,59],"varName":"optional"}}},{"id":166,"status":"applicable","file":"src/Api.elm","type":"UnusedTopLevel","data":{"description":"Unused top level definition `decode` at ((73,1),(73,7))","properties":{"range":[73,1,73,7],"varName":"decode"}}},{"id":163,"status":"applicable","file":"src/Api.elm","type":"UnusedPatternVariable","data":{"description":"Unused var

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onStdout (/Users/hpate/git/elm-ls/server/out/providers/diagnostics/elmAnalyseDiagnostics.js:96:44)
    at Socket.childProcess.stdout.on (/Users/hpate/git/elm-ls/server/out/util/elmUtils.js:31:17)
    at Socket.emit (events.js:187:15)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
[Error - 5:19:36 PM] Connection to server got closed. Server will not be restarted.
```

I'm working on updating it to the style I have in https://github.com/antew/elm-lsp where it loads the Elm app and communicates through ports, I have the diagnostics showing and updating on file change so far, I should have a PR in a day or two with it.

- The `exposed` and `local` annotations are working
- Hover type annotations work for things in the same file
- elm-make errors are showing up for me
- GoTo definition works well in the same file

One thing I was thinking about was separating out the `elm-make` errors and `elm-analyse` errors so that they can each report whenever they are done rather than running in sequence, the LS protocol is a little limited in this respect because you can't have separate diagnostics channels within one server, it replaces the previous diagnostics whenever you send them.  I was going to structure it so that the diagnostics provider keeps track of `elm make` and `elm-analyse` errors in different lists, and whenever diagnostics are going to be send to the client it concats the lists and sends that.  When each process runs it would update their portion of the list and the new version would be sent off.

Let me know if you see any issues with that or not, and thank you for all the work on this!!!

**Comment by Razzeee** [comment]
No, sounds wonderful and might be nice to use rxjs for that? But certainly not a must.
Most work i did there was just to get it to work anyhow.

I think we will need a way to expose diagnostics to other providers in the future.
So that we can for e.g. suggest a fix for a typo via the language server.

So a codeActionProvider would see that diagnostics have been updated, scan for certain errors and suggest things to do. https://code.visualstudio.com/api/language-extensions/programmatic-language-features#possible-actions-on-errors-or-warnings

**Comment by antew** [comment]
I've got a prototype of this going 
![quickfix](https://user-images.githubusercontent.com/1693421/57424902-50e3c800-71e7-11e9-972c-21487ad863b0.gif)

The biggest limitation right now is that it replaces the whole file to fix it, I'm going to do some work in elm-analyse to allow just the new text for the error range.

In the server version it formats the file after elm-analyse finishes, do you think we should do the same here?

**Comment by Razzeee** [comment]
Shouldn't formatting be something our elm format workflow should do?

**Comment by antew** [comment]
Yeah, I think the Elm format workflow should be used, I wasn't sure if it should run automatically after a quick fix is performed or whether it should let the user run it manually.

**Comment by Razzeee** [comment]
> Elm make tries to open the generated elm.js every time it runs. Pretty weird, hopefully just something that happens when you run the dev version.

Removed the `elm.js` from the main folder, problem is gone. I remember someone mentioning this over in the main elm compiler repo (but it's not an elm problem)

> Linux says it doesn't global installations, I do have them. So it might be my linux or a problem in general.

So it turns out that the path env we're getting from node/vscode is complete, but nvm paths will be removed. That's why we can't find them. The fix is making the path configurable as i did in #24

**Comment by Razzeee** [comment]
I feel like we do have tested the diagnostics providers quite a bit now and a general issue doesn't hel. Closing for now.

**Comment by Razzeee** [comment]
> I've got a prototype of this going
> ![quickfix](https://user-images.githubusercontent.com/1693421/57424902-50e3c800-71e7-11e9-972c-21487ad863b0.gif)
> 
> The biggest limitation right now is that it replaces the whole file to fix it, I'm going to do some work in elm-analyse to allow just the new text for the error range.
> 
> In the server version it formats the file after elm-analyse finishes, do you think we should do the same here?

@antew can you point me to a branch? it might be possible to just diff the files like we do for elm-format. But then again, it would be better to let elm-analyse do that, as the whole community would profit from that.

**Comment by antew** [comment]
That might be the best way to go about it, I haven't updated these branches in a bit but 
the elm-analyse part is on the `feature/lsp-fixer` branch: https://github.com/stil4m/elm-analyse/compare/master...antew:feature/lsp-fixer. 

The changes I made in elm-language-server are a lot messier, I had planned do some cleanup of my stuff, it's on a `feature/code-actions` branch at https://github.com/elm-tooling/elm-language-server/compare/master...antew:feature/code-actions

**Comment by Razzeee** [comment]
Can you explain what a quick fix is versus a fix? Is the elm-analyse branch ready? If yes, can you upstream it?

I can work through the needed language server changes, if that happens and you would like me to do that.

**Comment by antew** [comment]
For the quick fix vs fix it is to allow nicer interoperability with the language server. Normally when you call elm-analyse to run a fix it will read the file from disk, fix it, write it back to disk, and format it with elm-format.  The quick fix piece is there to allow it to work when the file hasn't been written to disk yet, and to send back the new file content rather than writing it to disk.

It isn't quite ready yet but I'll have some time to work on it this week and have it upstream-able after that.  

On the language server side I need to move up the `elmAnalyseDiagnostics` so that the same instance can be used for diagnostics as well as code actions (for speed and to prevent syncing issues), I started on it over in this one (https://github.com/elm-tooling/elm-language-server/compare/master...antew:feature/code-actions#diff-87377fe5c568eb8fd1cdf5c6f241e6ecR66), but the code is a bit jumbled now.

I expect I'll have PRs in to both projects by the end of this coming weekend.

**Comment by Razzeee** [comment]
It's good to know that your doing this, making diagnostics available everywhere was on my todo. We also want to process those and match them for e.g. for elm make suggestions (misspelled functions etc.)
