### ISSUE TITLE
No compiler feedback for test files

### ISSUE THREAD

**Issue by sentience** [elm-tooling/elm-language-server#144]
I'm just trying out the ElmLS extension in VS Code for the first time. Everything seems to be working fine for source files, but for test files I am only getting elm-analyze feedback and elm-format functionality. Even though `elm-test make` at the Terminal prompt correctly produces a compiler error, VS Code shows no problems in the file (only warnings from elm-analyze).

## Expected Behavior

Expected to see compiler errors shown as problems in test files.

## Current Behavior

No compiler errors shown in test files.

## Steps to Reproduce (for bugs)
1. Clone https://github.com/sentience/elm-test-app
2. Open the folder in VS Code
3. Open tests/Example.elm
4. Introduce a compiler error (like `suite : Test` → `suite : Foo`).
5. No problem is shown in the editor.

## Context
Using the extension for the first time. Doing some TDD of a feature in my app, but the absence of compiler feedback on my tests makes this inconvenient.

## Your Environment
* Version used: ElmLS 0.4.2
* Editor used: Visual Studio Code 1.38.0-insider
* Environment name and version (e.g. node.js 5.4): node.js 9.11.1
* Operating System and version: macOS 10.14.6

**Comment by Razzeee** [comment]
I'm getting this with your instructions and the current master version. Did you `save` the file between step 4 and 5?
![image](https://user-images.githubusercontent.com/5943908/63443190-a6f61780-c434-11e9-973a-1e3c18363106.png)

**Comment by andys8** [comment]
Can not reproduce, too.

![image](https://user-images.githubusercontent.com/13085980/64212058-71c3dd80-cea8-11e9-9adc-8ed0af37ff03.png)

![image](https://user-images.githubusercontent.com/13085980/64212080-8011f980-cea8-11e9-8c90-8aa01075477d.png)

It could be caused by not triggering compile (on save) or `elm-test` missing on `PATH` or at least not visible or wrongly configured or an implementation error in `elm-language-server` binary search (which I'm not seeing).

**Comment by andys8** [comment]
@sentience This could have been a duplicate of #158 (solved). Can you verify and confirm the issue is still occuring for you?

**Comment by sentience** [comment]
I can confirm this is fixed in the current release. Thanks!
