### ISSUE TITLE
`elm-analyse.json` is getting ignored

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#30]
I haven't been able to fully track down why, but settings in `elm-analyse.json` are getting ignored. As an example, if you have:
```
{
    "checks": {
        "ImportAll": false
    },
}
```
`elm-ls` still reports `ImportAll` warnings. 

From my digging, it looks like the port that loads `elm-analyse.json` is getting initialized correctly:
From [file-loading-ports](https://github.com/stil4m/elm-analyse/blob/455a42cba07012a67f498bca106d35688a179c95/ts/file-loading-ports.ts#L14) to [context](https://github.com/stil4m/elm-analyse/blob/455a42cba07012a67f498bca106d35688a179c95/ts/ports/context.ts).

I haven't poked the internals of elm-analyse to understand why it's ignoring them.

**Comment by Razzeee** [comment]
@antew can you have a look at one point?

**Comment by antew** [comment]
Yeah no problem, I'm on vacation until tomorrow but I'll be back tomorrow night and can check it out.

**Comment by Razzeee** [comment]
Take your time please, vacations are sacred :palm_tree:

**Comment by antew** [comment]
It looks like there are two bugs in how the `elm-analyse.json` file is handled.

1. I inadvertently introduced a timing bug in elm-analyse, if the first file change event happens in the language server before `elm-analyse` has loaded the configuration file it will skip the state where it is listening for the configuration and go with the default.
2. It would always try to load the configuration relative to the current working directory rather than the directory where `elm.json` is.

I'm still debating how to fix them, for `elm-analyse.json` I am leaning toward having it look up through parent directories so that you have the option of setting global configuration in `~/elm-analyse.json`.

For the timing bug the fix is either going to be passing in the configuration as a `flag`, or ignoring the file change messages until everything has loaded, I am leaning toward the `flag` approach at the moment because it seems cleaner and would make it easier to add Elm Analyse settings panes and whatnot later on.

I should be able to get in a PR for it tomorrow night.

**Comment by antew** [comment]
For the timing bug #42 should fix it, and for multi-projects where you might have `/project` open in an editor and the elm app is at `/project/web/` I put in a PR for elm-analyse over at https://github.com/stil4m/elm-analyse/pull/204

Cheers!

**Comment by andys8** [comment]
I had trouble before, but it's now working for me with a simple project structure where `elm.json` and `elm-analyse.json` are located in the project / git root.

**Comment by Razzeee** [comment]
This should be addressed by the PR linked above. Closing for now.

**Comment by dtrckd** [comment]
Hi there, 

I discovered that if I open a file (nvim + lspconfig, default config.) not from the root directory of the project (but typically from `<rootdir>/src`), the elm-analyse.json file is ignored (not send to the language server?).

Is it a know issue? Please tell me if you prefer that I open a new issue for this.

Thank you.
