### ISSUE TITLE
Run `elm make` on server initialization to download dependencies

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#344]
I think without passing an entry file path, it will just download the dependencies and quit, so it shouldn't affect startup time very much.

**Comment by kdmurthy** [comment]
If the `elm-stuff` folder exists and has already compiled packages, even `elm make` doesn't download the dependencies. My case is a bit specific since I use a docker container and load only the "Sources" folder. The user home is mounted as a internal volume. So If ever I delete the home volume, the `.elm` folder and with it all downloaded packages are gone. In that case just doing `elm make` is not enough. I need to remove `elm-stuff` folder and run make.
As I said, this is specific to my setup and don't know whether this needs to be handled.
